# 初始化主控机，安装gcc，git等依赖包
- name: init_ansible
  hosts: ansible
  roles:
    - init_ansible

# 所有机器创建相关目录，安装docker等
- name: init site
  hosts: all
  roles:
    - init

# 在ansible上创建证书
- name: general certs
  hosts: ansible
  roles:
    - certs

# 安装etcd，分发证书
- name: install etcd
  hosts: etcd
  roles:
    - etcd

# 主节点上安装APIServer，Controller Manager，Scheduler
- name: install server
  hosts: server
  roles:
    - server

# node节点安装服务 kubelet等
- name: install node
  hosts: all
  roles:
    - node

# 安装flannel
- name: install flannel
  hosts: all
  roles:
    - {role: flannel, when: cni_mode != "yes"}

# 安装addons
- name: install addons
  hosts: server
  roles:
    - addons

# 安装nginx
- name: install nginx
  hosts: lb
  roles:
    - { role: nginx, when: cluster_ha == "yes" }

# 增加一个新节点
- name: add new node
  hosts: new_node
  roles:
    - node