- name: "Distribute kube-proxy CSR File"
  copy:
    src: "kubernetes/kube-proxy-csr.json"
    dest: "{{ cert_root_dir }}/kubernetes/kube-proxy/"
  tags: certs, kube_proxy_certs, install_node

- name: "Generate kube-proxy Certs File and Key File"
  shell:
    cfssl gencert -ca=../ca.pem -ca-key=../ca-key.pem -config=../ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ cert_root_dir }}/kubernetes/kube-proxy/"
  tags: certs, kube_proxy_certs, install_node