- name: "Distribute Configuration File"
  template:
    src: kube-controller-manager.j2
    dest: "{{workdir}}/kubernetes/cfg/kube-controller-manager"
    force: true
  tags: install_server, install_controller_manager

- name: "Distribute Start Script"
  template:
    src: kube-controller-manager.service.j2
    dest: "/usr/lib/systemd/system/kube-controller-manager.service"
    force: true
  tags: install_server, install_controller_manager

- name: "Distribute Bin File"
  copy:
    src: "{{package_root_dir}}/kubernetes/server/bin/kube-controller-manager"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
  tags: install_server, install_controller_manager

- name: "Start Kube Controller Manager"
  systemd:
    name: kube-controller-manager
    enabled: true
    state: restarted
    daemon-reload: true
  tags: install_server, install_controller_manager