- name: "Clone Repository"
  git: 
    repo: "https://github.com/coredns/deployment.git"
    dest: "{{ package_root_dir }}/kubernetes/addons/coredns"
  tags: install_coredns

- name: "Install Core DNS"
  shell: |
    ./deploy.sh -i {{coredns_service_ip}} | kubectl apply -f -
  tags: install_coredns