- name: "Install new packages"
  yum:
    name: ['conntrack', 'ipvsadm', 'ipset', 'iptables-services', 'libseccomp', 'jq', 'sysstat', 'curl', 'wget', 'net-tools', 'telnet', 'vim', 'socat', 'unzip', 'git']
    state: present
  
- name: "Disable Selinux"
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    line: 'SELINUX=disabled'

- name: "Execute Disable Selinx Command"
  shell: setenforce 0
  ignore_errors: yes

- name: "Disable Swap"
  shell: swapoff -a

- name: "Disable Firewalld"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: "Clean Iptables Chains"
  shell: iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat && iptables -P FORWARD ACCEPT

- name: "Change System Variables"
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: "Apply System Variables"
  shell: modprobe br_netfilter && sysctl -p /etc/sysctl.d/k8s.conf

- name: "Change TimeZone"
  shell: timedatectl set-timezone Asia/Shanghai

- name: "Load IPVS Modules"
  shell: |
    modprobe -- ip_vs
    modprobe -- ip_vs_rr
    modprobe -- ip_vs_wrr
    modprobe -- ip_vs_sh
    modprobe -- nf_conntrack_ipv4